version: '2'
services:
    everisaragon-app:
        image: everisaragon
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://everisaragon-mysql:3306/everisaragon?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    everisaragon-mysql:
        extends:
            file: mysql.yml
            service: everisaragon-mysql
